apiVersion: v1
kind: Secret
metadata:
  name: {{ include "hookman.fullname" . }}
  labels:
    {{- include "hookman.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "config.databaseURL is required" .Values.config.databaseURL | quote }}
  API_KEY: {{ required "config.apiKey is required" .Values.config.apiKey | quote }}
  SIGNING_SECRET: {{ required "config.signingSecret is required" .Values.config.signingSecret | quote }}
