// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: delivery_attempts.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDeliveryAttempt = `-- name: CreateDeliveryAttempt :exec
INSERT INTO delivery_attempts (id, event_id, endpoint_id, attempt_number, http_status, response_body, duration_ms, status, attempted_at, next_retry_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, NOW(), $9)
`

type CreateDeliveryAttemptParams struct {
	ID            string             `json:"id"`
	EventID       string             `json:"event_id"`
	EndpointID    string             `json:"endpoint_id"`
	AttemptNumber int32              `json:"attempt_number"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	ResponseBody  pgtype.Text        `json:"response_body"`
	DurationMs    pgtype.Int4        `json:"duration_ms"`
	Status        string             `json:"status"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
}

func (q *Queries) CreateDeliveryAttempt(ctx context.Context, arg CreateDeliveryAttemptParams) error {
	_, err := q.db.Exec(ctx, createDeliveryAttempt,
		arg.ID,
		arg.EventID,
		arg.EndpointID,
		arg.AttemptNumber,
		arg.HttpStatus,
		arg.ResponseBody,
		arg.DurationMs,
		arg.Status,
		arg.NextRetryAt,
	)
	return err
}

const getDeliveryAttemptsByEndpoint = `-- name: GetDeliveryAttemptsByEndpoint :many
SELECT id, event_id, endpoint_id, attempt_number, http_status, response_body, duration_ms, status, attempted_at, next_retry_at
FROM delivery_attempts
WHERE endpoint_id = $1
ORDER BY attempted_at DESC
LIMIT $2
`

type GetDeliveryAttemptsByEndpointParams struct {
	EndpointID string `json:"endpoint_id"`
	Limit      int32  `json:"limit"`
}

func (q *Queries) GetDeliveryAttemptsByEndpoint(ctx context.Context, arg GetDeliveryAttemptsByEndpointParams) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, getDeliveryAttemptsByEndpoint, arg.EndpointID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptNumber,
			&i.HttpStatus,
			&i.ResponseBody,
			&i.DurationMs,
			&i.Status,
			&i.AttemptedAt,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDeliveryAttemptsByEvent = `-- name: GetDeliveryAttemptsByEvent :many
SELECT id, event_id, endpoint_id, attempt_number, http_status, response_body, duration_ms, status, attempted_at, next_retry_at
FROM delivery_attempts
WHERE event_id = $1
ORDER BY attempted_at ASC
`

func (q *Queries) GetDeliveryAttemptsByEvent(ctx context.Context, eventID string) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, getDeliveryAttemptsByEvent, eventID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptNumber,
			&i.HttpStatus,
			&i.ResponseBody,
			&i.DurationMs,
			&i.Status,
			&i.AttemptedAt,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRetryableAttempts = `-- name: GetRetryableAttempts :many
SELECT DISTINCT ON (da.event_id, da.endpoint_id)
  da.id, da.event_id, da.endpoint_id, da.attempt_number, da.http_status,
  da.response_body, da.duration_ms, da.status, da.attempted_at, da.next_retry_at
FROM delivery_attempts da
JOIN events e ON e.id = da.event_id
WHERE da.next_retry_at IS NOT NULL
  AND da.next_retry_at <= $1
  AND da.status = 'failed'
  AND e.status != 'dead'
ORDER BY da.event_id, da.endpoint_id, da.attempt_number DESC
LIMIT $2
`

type GetRetryableAttemptsParams struct {
	NextRetryAt pgtype.Timestamptz `json:"next_retry_at"`
	Limit       int32              `json:"limit"`
}

func (q *Queries) GetRetryableAttempts(ctx context.Context, arg GetRetryableAttemptsParams) ([]DeliveryAttempt, error) {
	rows, err := q.db.Query(ctx, getRetryableAttempts, arg.NextRetryAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeliveryAttempt{}
	for rows.Next() {
		var i DeliveryAttempt
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.EndpointID,
			&i.AttemptNumber,
			&i.HttpStatus,
			&i.ResponseBody,
			&i.DurationMs,
			&i.Status,
			&i.AttemptedAt,
			&i.NextRetryAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
