// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: endpoints.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createEndpoint = `-- name: CreateEndpoint :exec
INSERT INTO endpoints (id, url, topics, description, signing_secret, enabled, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, NOW(), NOW())
`

type CreateEndpointParams struct {
	ID            string      `json:"id"`
	Url           string      `json:"url"`
	Topics        []string    `json:"topics"`
	Description   pgtype.Text `json:"description"`
	SigningSecret string      `json:"signing_secret"`
	Enabled       bool        `json:"enabled"`
}

func (q *Queries) CreateEndpoint(ctx context.Context, arg CreateEndpointParams) error {
	_, err := q.db.Exec(ctx, createEndpoint,
		arg.ID,
		arg.Url,
		arg.Topics,
		arg.Description,
		arg.SigningSecret,
		arg.Enabled,
	)
	return err
}

const deleteEndpoint = `-- name: DeleteEndpoint :exec
DELETE FROM endpoints WHERE id = $1
`

func (q *Queries) DeleteEndpoint(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteEndpoint, id)
	return err
}

const getEndpoint = `-- name: GetEndpoint :one
SELECT id, url, topics, description, signing_secret, enabled, created_at, updated_at
FROM endpoints
WHERE id = $1
`

func (q *Queries) GetEndpoint(ctx context.Context, id string) (Endpoint, error) {
	row := q.db.QueryRow(ctx, getEndpoint, id)
	var i Endpoint
	err := row.Scan(
		&i.ID,
		&i.Url,
		&i.Topics,
		&i.Description,
		&i.SigningSecret,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEndpointsByTopic = `-- name: GetEndpointsByTopic :many
SELECT id, url, topics, description, signing_secret, enabled, created_at, updated_at
FROM endpoints
WHERE enabled = TRUE AND $1 = ANY(topics)
`

func (q *Queries) GetEndpointsByTopic(ctx context.Context, topics []string) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, getEndpointsByTopic, topics)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Topics,
			&i.Description,
			&i.SigningSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEndpoints = `-- name: ListEndpoints :many
SELECT id, url, topics, description, signing_secret, enabled, created_at, updated_at
FROM endpoints
ORDER BY created_at DESC
`

func (q *Queries) ListEndpoints(ctx context.Context) ([]Endpoint, error) {
	rows, err := q.db.Query(ctx, listEndpoints)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Endpoint{}
	for rows.Next() {
		var i Endpoint
		if err := rows.Scan(
			&i.ID,
			&i.Url,
			&i.Topics,
			&i.Description,
			&i.SigningSecret,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEndpoint = `-- name: UpdateEndpoint :exec
UPDATE endpoints
SET
  url = COALESCE($1, url),
  topics = COALESCE($2, topics),
  description = COALESCE($3, description),
  enabled = COALESCE($4, enabled),
  updated_at = NOW()
WHERE id = $5
`

type UpdateEndpointParams struct {
	Url         pgtype.Text `json:"url"`
	Topics      []string    `json:"topics"`
	Description pgtype.Text `json:"description"`
	Enabled     pgtype.Bool `json:"enabled"`
	ID          string      `json:"id"`
}

func (q *Queries) UpdateEndpoint(ctx context.Context, arg UpdateEndpointParams) error {
	_, err := q.db.Exec(ctx, updateEndpoint,
		arg.Url,
		arg.Topics,
		arg.Description,
		arg.Enabled,
		arg.ID,
	)
	return err
}
