// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: events.sql

package queries

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const bulkReplayDeadEvents = `-- name: BulkReplayDeadEvents :execrows
UPDATE events SET status = 'pending', updated_at = NOW()
WHERE status = 'dead'
`

func (q *Queries) BulkReplayDeadEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, bulkReplayDeadEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countEventsByStatus = `-- name: CountEventsByStatus :many
SELECT status, COUNT(*)::bigint AS count
FROM events
GROUP BY status
`

type CountEventsByStatusRow struct {
	Status string `json:"status"`
	Count  int64  `json:"count"`
}

func (q *Queries) CountEventsByStatus(ctx context.Context) ([]CountEventsByStatusRow, error) {
	rows, err := q.db.Query(ctx, countEventsByStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountEventsByStatusRow{}
	for rows.Next() {
		var i CountEventsByStatusRow
		if err := rows.Scan(&i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createEvent = `-- name: CreateEvent :exec
INSERT INTO events (id, topic, payload, idempotency_key, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, NOW(), NOW())
`

type CreateEventParams struct {
	ID             string      `json:"id"`
	Topic          string      `json:"topic"`
	Payload        []byte      `json:"payload"`
	IdempotencyKey pgtype.Text `json:"idempotency_key"`
	Status         string      `json:"status"`
}

func (q *Queries) CreateEvent(ctx context.Context, arg CreateEventParams) error {
	_, err := q.db.Exec(ctx, createEvent,
		arg.ID,
		arg.Topic,
		arg.Payload,
		arg.IdempotencyKey,
		arg.Status,
	)
	return err
}

const getDeadEvents = `-- name: GetDeadEvents :many
SELECT id, topic, payload, idempotency_key, status, created_at, updated_at
FROM events
WHERE status = 'dead'
  AND ($1::text IS NULL OR id < $1)
ORDER BY updated_at DESC
LIMIT $2
`

type GetDeadEventsParams struct {
	BeforeID   pgtype.Text `json:"before_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) GetDeadEvents(ctx context.Context, arg GetDeadEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, getDeadEvents, arg.BeforeID, arg.LimitCount)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEvent = `-- name: GetEvent :one
SELECT id, topic, payload, idempotency_key, status, created_at, updated_at
FROM events
WHERE id = $1
`

func (q *Queries) GetEvent(ctx context.Context, id string) (Event, error) {
	row := q.db.QueryRow(ctx, getEvent, id)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getEventByIdempotencyKey = `-- name: GetEventByIdempotencyKey :one
SELECT id, topic, payload, idempotency_key, status, created_at, updated_at
FROM events
WHERE idempotency_key = $1
`

func (q *Queries) GetEventByIdempotencyKey(ctx context.Context, idempotencyKey pgtype.Text) (Event, error) {
	row := q.db.QueryRow(ctx, getEventByIdempotencyKey, idempotencyKey)
	var i Event
	err := row.Scan(
		&i.ID,
		&i.Topic,
		&i.Payload,
		&i.IdempotencyKey,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingEvents = `-- name: GetPendingEvents :many
SELECT id, topic, payload, idempotency_key, status, created_at, updated_at
FROM events
WHERE status = 'pending'
ORDER BY created_at ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) GetPendingEvents(ctx context.Context, limit int32) ([]Event, error) {
	rows, err := q.db.Query(ctx, getPendingEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listEvents = `-- name: ListEvents :many
SELECT id, topic, payload, idempotency_key, status, created_at, updated_at
FROM events
WHERE
  ($1::text IS NULL OR topic = $1) AND
  ($2::text IS NULL OR status = $2) AND
  ($3::text IS NULL OR id < $3)
ORDER BY id DESC
LIMIT $4
`

type ListEventsParams struct {
	Topic      pgtype.Text `json:"topic"`
	Status     pgtype.Text `json:"status"`
	BeforeID   pgtype.Text `json:"before_id"`
	LimitCount int32       `json:"limit_count"`
}

func (q *Queries) ListEvents(ctx context.Context, arg ListEventsParams) ([]Event, error) {
	rows, err := q.db.Query(ctx, listEvents,
		arg.Topic,
		arg.Status,
		arg.BeforeID,
		arg.LimitCount,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Event{}
	for rows.Next() {
		var i Event
		if err := rows.Scan(
			&i.ID,
			&i.Topic,
			&i.Payload,
			&i.IdempotencyKey,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const purgeDeadEvents = `-- name: PurgeDeadEvents :execrows
DELETE FROM events WHERE status = 'dead'
`

func (q *Queries) PurgeDeadEvents(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, purgeDeadEvents)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateEventStatus = `-- name: UpdateEventStatus :exec
UPDATE events SET status = $2, updated_at = NOW() WHERE id = $1
`

type UpdateEventStatusParams struct {
	ID     string `json:"id"`
	Status string `json:"status"`
}

func (q *Queries) UpdateEventStatus(ctx context.Context, arg UpdateEventStatusParams) error {
	_, err := q.db.Exec(ctx, updateEventStatus, arg.ID, arg.Status)
	return err
}
