// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DeliveryAttempt struct {
	ID            string             `json:"id"`
	EventID       string             `json:"event_id"`
	EndpointID    string             `json:"endpoint_id"`
	AttemptNumber int32              `json:"attempt_number"`
	HttpStatus    pgtype.Int4        `json:"http_status"`
	ResponseBody  pgtype.Text        `json:"response_body"`
	DurationMs    pgtype.Int4        `json:"duration_ms"`
	Status        string             `json:"status"`
	AttemptedAt   pgtype.Timestamptz `json:"attempted_at"`
	NextRetryAt   pgtype.Timestamptz `json:"next_retry_at"`
}

type Endpoint struct {
	ID            string             `json:"id"`
	Url           string             `json:"url"`
	Topics        []string           `json:"topics"`
	Description   pgtype.Text        `json:"description"`
	SigningSecret string             `json:"signing_secret"`
	Enabled       bool               `json:"enabled"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type Event struct {
	ID             string             `json:"id"`
	Topic          string             `json:"topic"`
	Payload        []byte             `json:"payload"`
	IdempotencyKey pgtype.Text        `json:"idempotency_key"`
	Status         string             `json:"status"`
	CreatedAt      pgtype.Timestamptz `json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `json:"updated_at"`
}
